# Generated by Django 5.2.1 on 2025-05-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('multiple-choice', 'Множественный выбор'), ('text-input', 'Текстовый ввод')], max_length=20)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('correct_answers', models.JSONField()),
            ],
        ),
    ]
